version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-container
    ports:
      - "3306:3306"                      # Expose le port 3306 pour MySQL
    volumes:
      - mysql_data:/var/lib/mysql         # Volume pour la persistance des données
    networks:
      - app-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/kaddem?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
    ports:
      - "8090:8090"                       # Expose le port 8089 pour ton application Spring Boot
    depends_on:
      - mysql                              # S'assure que MySQL démarre avant Spring Boot
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge